DROP DATABASE IF EXISTS SIUMBA;
CREATE DATABASE SIUMBA;
USE SIUMBA;

CREATE TABLE CLIENTES(
ID_CLIENTE INT PRIMARY KEY UNIQUE NOT NULL,
NOMBRE VARCHAR(20),
DIRECCION VARCHAR(100),
TELEFONO VARCHAR(12)
);

CREATE TABLE FACTURAS(
ID_FACTURA INT PRIMARY KEY NOT NULL UNIQUE,
FECHA DATE,
ID_CLIENTE INT,
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);

CREATE TABLE PROVEEDORES(
ID_PROVEEDOR INT PRIMARY KEY NOT NULL UNIQUE,
NOMBRE VARCHAR(20),
DIRECCION VARCHAR(100),
TELEFONO VARCHAR(12)
);


CREATE TABLE CATEGORIAS(
ID_CATEGORIA INT PRIMARY KEY NOT NULL UNIQUE,
DESCRIPCION VARCHAR(300)
);

CREATE TABLE PRODUCTOS(
ID_PRODUCTO INT PRIMARY KEY NOT NULL UNIQUE,
DESCRIPCION VARCHAR(200),
PRECIO DECIMAL (10,2), /*10 ES LA LONGITUD TOTAL Y 2 LOS DECIMALES*/
ID_CATEGORIA INT,
ID_PROVEEDOR INT,
FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA),
FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR)
);

CREATE TABLE VENTAS (
ID_VENTA INT PRIMARY KEY NOT NULL UNIQUE,
ID_FACTURA INT,
ID_PRODUCTO INT,
CANTIDAD INT,
FOREIGN KEY (ID_FACTURA) REFERENCES FACTURAS(ID_FACTURA),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

ALTER TABLE CLIENTES
ADD COLUMN DNI NUMERIC(8),
MODIFY COLUMN DIRECCION VARCHAR(300),
ADD COLUMN CIUDAD VARCHAR(50),
ADD COLUMN `Código Postal` NUMERIC (5),
ADD COLUMN VIP BOOLEAN, /* 1 SERIA TRUE Y 0 SERIA FALSE*/
ADD COLUMN EDAD INT,
ADD CHECK (EDAD>=18)
;

ALTER TABLE PRODUCTOS
ADD COLUMN NOMBRE VARCHAR(200) NOT NULL,
ADD COLUMN CANTIDAD INT,
ADD CHECK (CANTIDAD<=9999 AND CANTIDAD>=0);

ALTER TABLE CATEGORIAS
ADD COLUMN TIPO VARCHAR (20),
ADD CHECK (TIPO ='LIMPIEZA' ^ TIPO='ALIMENTOS' ^ TIPO='BELLEZA'),
ADD COLUMN SUBTIPO VARCHAR (20),
ADD CHECK(SUBTIPO='NORMAL' OR  SUBTIPO='PREMIUM');

CREATE TABLE CIUDADES(
ID_CIUDAD INT PRIMARY KEY UNIQUE NOT NULL, 
CIUDAD VARCHAR(20) NOT NULL
);

CREATE TABLE FABRICANTES(
ID_FABRICANTE INT PRIMARY KEY NOT NULL UNIQUE,
NOMBRE VARCHAR(20) NOT NULL,
DIRECCION VARCHAR(300) NOT NULL,
PAIS VARCHAR(20) NOT NULL,
CHECK (PAIS='ES' ^ PAIS='EN' ^ PAIS='PT'),
TELEFONO NUMERIC(11) NOT NULL,
ID_CIUDAD INT NOT NULL,
FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDADES(ID_CIUDAD)
                                                     /*CONSTRAINT PK_IDIER PRIMARY KEY (ID_FABRISANTE,ID_PORODCUTO)*/
);

ALTER TABLE PRODUCTOS
ADD COLUMN ID_FABRICANTE INT,
ADD FOREIGN KEY (ID_FABRICANTE) REFERENCES FABRICANTES(ID_FABRICANTE),
ADD COLUMN DIRECCION VARCHAR(150) NOT NULL,
ADD COLUMN PAIS VARCHAR(20) NOT NULL,
ADD COLUMN TELEFONO NUMERIC(15) NOT NULL,
ADD COLUMN CIUDAD VARCHAR(20) NOT NULL
CHECK (CIUDAD='ES' OR CIUDAD='EN' OR CIUDAD='PT');


/*INSERT INTO PRODUCTOS(ID_PRODUCTO,PRECIO,CANTIDAD) VALUES

('1000','120.64','5222'), -- Habria que añadir un nombre ya que esta declarado como not null
('1525','64.99','1250'), --  Habria que añadir un nombre ya que esta declarado como not null
('9999','36.04','1000'), --  Habria que añadir un nombre ya que esta declarado como not null
('2222','1260.63','6750'); --  Habria que añadir un nombre ya que esta declarado como not null */


INSERT INTO CLIENTES (ID_CLIENTE,NOMBRE,EDAD,DIRECCION) VALUES
/*(1,'Jesus',13,'Calle Rosa'), NO SE PUEDE AÑADIR A JESU QUE ES MENOR DE 18 E INCUMPLE EL CHEK DE EDAD QUE HICIMOS*/
(2,'María',55,'Calle Clavel'),
(3,'Maria',60,'Calle Lavando'),
(4,'Antonia',99,'Calle Jacinto ');

UPDATE CLIENTES 
SET VIP = IF (VIP=1 ,VIP='ES VIP',VIP='NO ES VIP'); /* SET PARA MODIFICAR DATO = IF (CONDICION , LO QUE PASA SI SE CUMPLE, LO QUE PASA SINO)*/

ALTER TABLE FACTURAS
ADD COLUMN `FECHA DE PAGO` DATE,
ADD COLUMN TARDANZA INT;

UPDATE FACTURAS
SET TARDANZA = DATEDIFF(`FECHA DE PAGO`,FECHA);

ALTER TABLE FACTURAS
ADD COLUMN RECARGO VARCHAR(4);

UPDATE FACTURAS
SET RECARGO = IF(TARDANZA>=90,'+10%', IF (TARDANZA>=120,'+15%',IF(TARDANZA>=150,'+20%','+0%')));

CREATE TABLE `NUEVOS CLIENTES` AS  /*ESTO ES CREAR UNA TABLE  EN BASE A OTRA Y AL PONER * SLECCIONAMOS TODOS LOS CAMPOS QUE TENGA ESA TABLA*/

SELECT *
FROM CLIENTES;

ALTER TABLE PRODUCTOS
DROP FOREIGN KEY PRODUCTOS_IBFK_3; 

DROP TABLE FABRICANTES;  


ALTER TABLE PRODUCTOS
DROP FOREIGN KEY PRODUCTOS_IBFK_1;

ALTER TABLE CATEGORIAS
DROP COLUMN ID_CATEGORIA;


ALTER TABLE VENTAS
DROP  FOREIGN KEY VENTAS_IBFK_1;

TRUNCATE TABLE FACTURAS;

DROP DATABASE SIUMBA;















